### ISSUE TITLE
Recovery always fails at the same point

### ISSUE THREAD

**Issue by renki81** [JackSlateur/bareos-libcloud#4]
I was able to create a backup of a ceph RGW. However, the recovery always fails at the same point. 
I only restore the one directory where the error occurs the restore works 

Fatal error: python-fd: Traceback (most recent call last):
File "/usr/lib/bareos/plugins/BareosFdWrapper.py", line 66, in create_file
return bareos_fd_plugin_object.create_file(context, restorepkt)
File "/usr/lib/bareos/plugins/BareosFdPluginBaseclass.py", line 311, in create_file
open(FNAME, 'wb').close()
IOError: (21, 'Is a directory', '/tmp/restore/testbackup/import-source/')

bareos-dir JobId 588: Error: Bareos bareos-dir 17.2.4 (21Sep17):
Build OS: x86_64-pc-linux-gnu debian Debian GNU/Linux 9.3 (stretch)
JobId: 588
Job: RestoreFiles.2019-04-09_21.23.03_11
Restore Client: bsv-01-fd
Start time: 09-Apr-2019 21:23:05
End time: 09-Apr-2019 21:40:32
Elapsed time: 17 mins 27 secs
Files Expected: 37,985
Files Restored: 36,623
Bytes Restored: 9,016,919,200
Rate: 8612.1 KB/s
FD Errors: 1
FD termination status: Fatal Error
SD termination status: Fatal Error
Termination: *** Restore Error ***

**Comment by renki81** [comment]
I was able to solve the problem myself. For some reason you can create a directory permission on the S3 over a S3 client. Unfortunately this can happen automatically. This leads to the python plugin assuming during restore that a file should be restored instead of a directory.

If you uncheck the python plugin on the bareos-fd then the files can be restored without being aborted. However, every file that is restored writes the error `Error: create_file.c:515 Zero length filename:`
